---
- hosts: mygroup
  become: yes
  tasks:
  - name: install java on ubuntu node
    apt:
      name: "{{myjavaubuntu}}"
      state: present
    when: ansible_os_family=="Debian"
  - name: install java on redhat node
    yum:
      name: "{{myjavaubuntu}}"
      state: present
    when: ansible_os_family=="RedHat"