---
- hosts: 172.31.41.100
  become: yes
  tasks: 
  - name: execute linux commands
    command: hostname -f
    register: myresult
  - name: i want to display my first task results
    debug:
      msg: "{{myresult}}"
  - name: install git
    apt:
      name: git
      state: present
    when: myresult.stderr!=" "
  - name: install apache2
    apt:
      name: apache2
      state: present
    when: myresult.stderr==" "