---
- hosts: 172.31.41.100
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install apache2
    apt:
      name: apache2
      state: present
  - name: copy file into ansible node side
    copy:
      src: staticfile.txt
      dest: /home/ubuntu/mystaticfile.txt
    ignore_errors: true
  - name: download files from internet 
    ansible.builtin.get_url:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes
  handlers:
  - name: restartwebserver
    service:
      name: apache2
      state: restarted 
  - name: install tree
    apt: 
      name: tree
      state: present
    notify: restartwebserver