---
- hosts: 172.31.41.100
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install apache2
    apt:
      name: apache2
      state: present
  - name: copy file into ansible node side
    copy:
      src: staticfile.txt
      dest: /home/ubuntu/mystaticfile.txt