---
- hosts: mygroup
  become: yes
  tasks:
  - name: i want install apache on ubuntu node
    apt: 
      name: "{{webpackonubuntu}}"
      state: present
    when: ansible_os_family=="Debian"
  - name: i want start webserver on ubuntu node
    service:
      name: "{{webpackonubuntu}}"
      state: started
    when: ansible_os_family=="Debian"
  - name: i want install apache on redhat node
    yum:
      name: "{{webpackonredhat}}"
      state: present
    when: ansible_os_family=="RedHat"
  - name: iwant start webserver on amazon node
    service:
      name: "{{webpackonredhat}}"
      state: started
    when: ansible_os_family=="RedHat"